version: "3.9"

# All the services needed to run the whole stack
services:

  # The actual server that front end(s) will be connected to and request data from
  weather_backend:
    container_name: weather-server
    image: weather-server
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3456:${BACKEND_PORT}"
    volumes:
      - ./backend:/usr/src/app/dev
      - ignore:/usr/src/app/dev/node_modules/
    depends_on:
      - weatherdb

  # The backend will connect to this database server. This will be completely
  # its own instance
  weatherdb:
    container_name: weather-database
    image: weather-database
    # Using the build context just to be able to rename the docker image
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
      - weatherdb-data:/var/lib/postgresql/data

# Volume mapped to database to preserve data when container is rebuilt
volumes:
  ignore:
  weatherdb-data: {}
